
entity_browser.browser.display.aside:
  type: mapping
  label: 'UX Aside display configuration'
  mapping:
    width:
      type: string
      label: 'UX Aside width'
    height:
      type: string
      label: 'UX Aside height'
    link_text:
      type: string
      label: 'Link text'
    auto_open:
      type: boolean
      label: 'Auto open'
