views.filter.ux_filter_entity_reference:
  type: views.filter.many_to_one
  label: 'UX Filter Entity reference'
  mapping:
    target_bundles:
      type: sequence
      label: 'types'
      nullable: true
      sequence:
        type: string
        label: 'Type'
    sort:
      type: mapping
      label: 'Sort settings'
      mapping:
        field:
          type: string
          label: 'Sort by'
        direction:
          type: string
          label: 'Sort direction'

views.filter_value.ux_filter_date:
  type: views.filter_value.numeric
  label: 'UX Filter Date'
  mapping:
    type:
      type: string
      label: 'Type'
    date_only:
      type: boolean
      label: 'Date only'
